name: Unit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Format and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Go Vet
        run: go vet ./...

      - name: Check gofmt
        run: |
          gofmt_files=$(gofmt -l .)
          if [ -n "$gofmt_files" ]; then
            echo "The following files are not gofmt formatted:"
            echo "$gofmt_files"
            exit 1
          fi
